force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Stores Individual Candidates for the Title, globally</description>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>This Email Governs the SITE login Authenticity.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nominee__c/Nominee__c.object-meta.xml
<CustomObject>
    <description>Stores Designated Nominees for a Title to be Voted upon</description>
    <label>Nominee</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Nominee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nominee__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <inlineHelpText>The Designated Candidate</inlineHelpText>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Nominees</relationshipLabel>
    <relationshipName>Nominees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nominee__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Nominees</relationshipLabel>
    <relationshipName>Nominees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Stores Team Names for Project Titles and Votes</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <description>Stores the Title / Honour / Merit / Rank to be Voted upon.</description>
    <label>Title</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Title__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Titles</relationshipLabel>
    <relationshipName>Titles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Title_Description__c.field-meta.xml
<CustomField>
    <fullName>Title_Description__c</fullName>
    <inlineHelpText>Description / Details / Elaborated Context</inlineHelpText>
    <label>Title Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <description>Stores Individual Votes against Each Nominee</description>
    <label>Vote</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Received Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/wbb_VoteControllerTest.cls
@isTest(SeeAllData = false)
public class wbb_VoteControllerTest {

    /*
    * @Method Name                    :  getTestingUser
    * @Description                    :  Creates a Test User
    * @Return Type                    :  User
    * @Parameters                     :  None
    */
    public static User getTestingUser() {

        String dateString = String.valueof(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '');
        Integer randomInt = Integer.valueOf(math.rint(math.random() * 1000000));
        String uniqueName = dateString + randomInt;

        User u;
        String pId = [select Id from Profile where Name = 'System Administrator'].Id;
        u = new User(profileId = pId, email = uniqueName + '@test' + uniqueName + '.gmail.com',
                     Username = uniqueName + '@test' + uniqueName +  'gmail.com',
                     alias = 'uqusr', lastname = 'lastname', emailencodingkey = 'UTF-8', localesidkey = 'en_US',
                     languagelocalekey = 'en_US', timezonesidkey = 'GMT');
        insert u;
        system.assertNotEquals(NULL, u);
        return u;
    }

    /*
    * @Method Name                    :  setup
    * @Description                    :  Creates Setup data for the test class
    * @Return Type                    :  User
    * @Parameters                     :  None
    */

    @TestSetup static void setup() {

        Team__c oTeam = new Team__c(Name = 'Test Team');
        insert oTeam;
        system.assertNotEquals(NULL, oTeam);

        List<Title__c> lTitle = new List<Title__c>();
        For(Integer i = 1; i < 5; i++) {
            Title__c oT = new Title__c(Name = 'Test Title ' + i, Team__c = oTeam.Id, Order__c = i, Title_Description__c  = 'Test Description ' + i);
            lTitle.add(oT);
        }
        insert lTitle;
        system.assertNotEquals(NULL, lTitle);

        List<Candidate__c > lCan = new List<Candidate__c >();
        For(Integer i = 1; i < 10; i++) {
            Candidate__c  oCan = new Candidate__c (Name = 'Test Candidate ' + i, Team__c = oTeam.Id, Email__c = 'TestEmail' + i + '@gmail.com');
            lCan.add(oCan);
        }
        insert lCan;
        system.assertNotEquals(NULL, lCan);

        Nominee__c  oNom = new Nominee__c (Title__c  = lTitle[0].id, Candidate__c = lCan[2].id);
        insert oNom;
        oNom = new Nominee__c (Title__c  = lTitle[0].id, Candidate__c = lCan[3].id);
        insert oNom;
        system.assertNotEquals(NULL, oNom);

    }

    /*
    * @Method Name                    :  test_verifyCandidate
    * @Description                    :  Method to Test verifyCandidate
    * @Return Type                    :  None
    * @Parameters                     :  None
    */

    static testMethod void test_verifyCandidate() {
        User u = getTestingUser();
        System.runAs(u) {
            Test.StartTest();
            system.assertEquals(wbb_VoteController.verifyCandidate('fail@w.com').voterName, '');
            system.assertNotEquals(wbb_VoteController.verifyCandidate('TestEmail1@gmail.com').voterName, '');
            Test.StopTest();
        }
    }


    /*
    * @Method Name                    :  test_castVote
    * @Description                    :  Method to Test castVote
    * @Return Type                    :  None
    * @Parameters                     :  None
    */

    static testMethod void test_castVote() {
        User u = getTestingUser();
        List<Title__c> lTitle = new List<Title__c>();
        lTitle = [SELECT id FROM Title__c LIMIT 100];

        List<Candidate__c > lCan = new List<Candidate__c >();
        lCan = [SELECT id, Name FROM Candidate__c LIMIT 100];

        map<string, string> mVote = new map<string, string>();
        mVote.put(lTitle[0].id, lCan[2].Name);
        mVote.put(lTitle[1].id, lCan[2].Name);
        mVote.put(lTitle[2].id, lCan[2].Name);

        System.runAs(u) {
            Test.StartTest();
            string voterID = wbb_VoteController.verifyCandidate('TestEmail1@gmail.com').voterID;
            system.assertNotEquals(wbb_VoteController.castVote(mVote, voterID), NULL);
            system.assertNotEquals([SELECT id FROM Vote__c LIMIT 100].size(), 0);
            system.assertNotEquals(wbb_VoteController.verifyCandidate('TestEmail1@gmail.com').lBox, NULL);
            Test.StopTest();
        }
    }


}